### PR TITLE
Add docker bootstrap container

### PR DESCRIPTION
**Pull request by poma**
Add a container that contains all prerequisites for spinning up k8s cluster and generating custom configs

// Don't forget to add this repo to auto builds on docker hub (readme references this container as `jpmorganchase/qubernetes`

### CODE REVIEW

**Comment by libby** [comment]
Thanks @poma this is great!

**Comment by libby** [comment]
@poma can you please complete the [CLA](https://github.com/jpmorganchase/cla/blob/master/cla-2016-09-01.pdf) and email it to quorum_cla@jpmorgan.com? So that we can merge this nice docker setup?

**Comment by poma** [comment]
Sent. Would be cool to implement digitally signing this via docuSign for example. Could be integrated via cla-assistant bot or via custom bot like in `github.com/elastic` repositories, or even via manual links.

**Comment by fixanoid** [comment]
@poma Thanks for signing CLA

**Pull request merged**
